// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2024-07-16 16:42:22.90573 &#43;0900 KST m=&#43;0.007864501
// using data from coins.yml
package coin

import (
	"fmt"
)

const (
	coinPrefix  = "c"
	tokenPrefix = "t"
)

// Coin is the native currency of a blockchain
type Coin struct {
	ID               uint
	Handle           string
	Symbol           string
	Name             string
	Decimals         uint
	BlockTime        int
	MinConfirmations int64
	Blockchain       string // Name of the Blockchain which core is used for this network
	IsTokenSupported bool 	// Indicate whether the backend supports token parsing for this network
}

type AssetID string

func (c *Coin) String() string {
	return fmt.Sprintf("[%s] %s (#%d)", c.Symbol, c.Name, c.ID)
}

func (c Coin) AssetID() AssetID {
	return AssetID(coinPrefix + fmt.Sprint(c.ID))
}

func (c Coin) TokenAssetID(t string) AssetID {
	result := c.AssetID()
	if len(t) > 0 {
		result += AssetID("_" + tokenPrefix + t)
	}

	return result
}

const (
	ETHEREUM = 60
	CLASSIC = 61
	ICON = 74
	COSMOS = 118
	RIPPLE = 144
	STELLAR = 148
	POA = 178
	TRON = 195
	FIO = 235
	NIMIQ = 242
	IOTEX = 304
	IOTEXEVM = 10004689
	ZILLIQA = 313
	AION = 425
	AETERNITY = 457
	KAVA = 459
	THETA = 500
	BINANCE = 714
	VECHAIN = 818
	CALLISTO = 820
	TOMOCHAIN = 889
	THUNDERTOKEN = 1001
	ONTOLOGY = 1024
	TEZOS = 1729
	KIN = 2017
	NEBULAS = 2718
	GOCHAIN = 6060
	WANCHAIN = 5718350
	WAVES = 5741564
	BITCOIN = 0
	LITECOIN = 2
	DOGE = 3
	DASH = 5
	VIACOIN = 14
	GROESTLCOIN = 17
	ZCASH = 133
	FIRO = 136
	BITCOINCASH = 145
	RAVENCOIN = 175
	QTUM = 2301
	ZELCASH = 19167
	DECRED = 42
	ALGORAND = 283
	NANO = 165
	DIGIBYTE = 20
	HARMONY = 1023
	KUSAMA = 434
	POLKADOT = 354
	SOLANA = 501
	NEAR = 397
	ELROND = 508
	SMARTCHAIN = 20000714
	FILECOIN = 461
	OASIS = 474
	MONACOIN = 22
	BITCOINGOLD = 156
	EOS = 194
	TERRA = 330
	BAND = 494
	NEO = 888
	CARDANO = 1815
	NULS = 8964
	POLYGON = 966
	THORCHAIN = 931
	OPTIMISM = 10000070
	XDAI = 10000100
	AVALANCHEC = 10009000
	HECO = 10000553
	FANTOM = 10000250
	ARBITRUM = 10042221
	CELO = 52752
	RONIN = 10002020
	OSMOSIS = 10000118
	CRONOS = 10000025
	KCC = 10000321
	AURORA = 1323161554
	KAVAEVM = 10002222
	METER = 18000
	EVMOS = 10009001
	NATIVEEVMOS = 20009001
	OKC = 996
	CRYPTOORG = 394
	APTOS = 637
	MOONBEAM = 10001284
	KLAYTN = 10008217
	METIS = 10001088
	MOONRIVER = 10001285
	BOBA = 10000288
	TON = 607
	POLYGONZKEVM = 10001101
	ZKSYNC = 10000324
	SUI = 784
	STRIDE = 40000118
	NEUTRON = 90000118
	STARGAZE = 20000118
	NATIVEINJECTIVE = 10000060
	CFXEVM = 1030
	ACALA = 787
	ACALAEVM = 10000787
	BASE = 8453
	AKASH = 17000118
	AGORIC = 564
	AXELAR = 50000118
	JUNO = 30000118
	SEI = 19000118
	NEON = 245022934
	OPBNB = 204
	LINEA = 59144
	GBNB = 5600
	MANTLE = 5000
	MANTA = 169
	ZETACHAIN = 10007000
	ZETAEVM = 20007000
	MERLIN = 4200
	BLAST = 81457
	SCROLL = 534352
	INTERNET_COMPUTER = 223
	BOUNCEBIT = 6001
	ZKLINKNOVA = 810180
)

var Coins = map[uint]Coin{
	ETHEREUM: {
		ID:               60,
		Handle:           "ethereum",
		Symbol:           "ETH",
		Name:             "Ethereum",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	CLASSIC: {
		ID:               61,
		Handle:           "classic",
		Symbol:           "ETC",
		Name:             "Ethereum Classic",
		Decimals:         18,
		BlockTime:        30000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	ICON: {
		ID:               74,
		Handle:           "icon",
		Symbol:           "ICX",
		Name:             "ICON",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 0,
		Blockchain:       "Icon",
		IsTokenSupported: false,
	},
	COSMOS: {
		ID:               118,
		Handle:           "cosmos",
		Symbol:           "ATOM",
		Name:             "Cosmos",
		Decimals:         6,
		BlockTime:        5000,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	RIPPLE: {
		ID:               144,
		Handle:           "ripple",
		Symbol:           "XRP",
		Name:             "Ripple",
		Decimals:         6,
		BlockTime:        5000,
		MinConfirmations: 0,
		Blockchain:       "Ripple",
		IsTokenSupported: false,
	},
	STELLAR: {
		ID:               148,
		Handle:           "stellar",
		Symbol:           "XLM",
		Name:             "Stellar",
		Decimals:         7,
		BlockTime:        5000,
		MinConfirmations: 0,
		Blockchain:       "Stellar",
		IsTokenSupported: false,
	},
	POA: {
		ID:               178,
		Handle:           "poa",
		Symbol:           "POA",
		Name:             "Poa",
		Decimals:         18,
		BlockTime:        5000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	TRON: {
		ID:               195,
		Handle:           "tron",
		Symbol:           "TRX",
		Name:             "Tron",
		Decimals:         6,
		BlockTime:        10000,
		MinConfirmations: 0,
		Blockchain:       "Tron",
		IsTokenSupported: true,
	},
	FIO: {
		ID:               235,
		Handle:           "fio",
		Symbol:           "FIO",
		Name:             "FIO",
		Decimals:         9,
		BlockTime:        5000,
		MinConfirmations: 0,
		Blockchain:       "FIO",
		IsTokenSupported: false,
	},
	NIMIQ: {
		ID:               242,
		Handle:           "nimiq",
		Symbol:           "NIM",
		Name:             "Nimiq",
		Decimals:         5,
		BlockTime:        60000,
		MinConfirmations: 0,
		Blockchain:       "Nimiq",
		IsTokenSupported: false,
	},
	IOTEX: {
		ID:               304,
		Handle:           "iotex",
		Symbol:           "IOTX",
		Name:             "IoTeX",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 0,
		Blockchain:       "IoTeX",
		IsTokenSupported: false,
	},
	IOTEXEVM: {
		ID:               10004689,
		Handle:           "iotexevm",
		Symbol:           "IOTX",
		Name:             "IoTeX Network Mainnet",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	ZILLIQA: {
		ID:               313,
		Handle:           "zilliqa",
		Symbol:           "ZIL",
		Name:             "Zilliqa",
		Decimals:         12,
		BlockTime:        30000,
		MinConfirmations: 1,
		Blockchain:       "Zilliqa",
		IsTokenSupported: false,
	},
	AION: {
		ID:               425,
		Handle:           "aion",
		Symbol:           "AION",
		Name:             "Aion",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 0,
		Blockchain:       "Aion",
		IsTokenSupported: false,
	},
	AETERNITY: {
		ID:               457,
		Handle:           "aeternity",
		Symbol:           "AE",
		Name:             "Aeternity",
		Decimals:         18,
		BlockTime:        6000,
		MinConfirmations: 0,
		Blockchain:       "Aeternity",
		IsTokenSupported: false,
	},
	KAVA: {
		ID:               459,
		Handle:           "kava",
		Symbol:           "KAVA",
		Name:             "Kava",
		Decimals:         6,
		BlockTime:        5000,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	THETA: {
		ID:               500,
		Handle:           "theta",
		Symbol:           "THETA",
		Name:             "Theta",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Theta",
		IsTokenSupported: true,
	},
	BINANCE: {
		ID:               714,
		Handle:           "binance",
		Symbol:           "BNB",
		Name:             "BNB",
		Decimals:         8,
		BlockTime:        1000,
		MinConfirmations: 2,
		Blockchain:       "Binance",
		IsTokenSupported: true,
	},
	VECHAIN: {
		ID:               818,
		Handle:           "vechain",
		Symbol:           "VET",
		Name:             "VeChain Token",
		Decimals:         18,
		BlockTime:        20000,
		MinConfirmations: 0,
		Blockchain:       "Vechain",
		IsTokenSupported: true,
	},
	CALLISTO: {
		ID:               820,
		Handle:           "callisto",
		Symbol:           "CLO",
		Name:             "Callisto",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	TOMOCHAIN: {
		ID:               889,
		Handle:           "tomochain",
		Symbol:           "TOMO",
		Name:             "TOMO",
		Decimals:         18,
		BlockTime:        4000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	THUNDERTOKEN: {
		ID:               1001,
		Handle:           "thundertoken",
		Symbol:           "TT",
		Name:             "ThunderCore",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	ONTOLOGY: {
		ID:               1024,
		Handle:           "ontology",
		Symbol:           "ONT",
		Name:             "Ontology",
		Decimals:         0,
		BlockTime:        10000,
		MinConfirmations: 0,
		Blockchain:       "Ontology",
		IsTokenSupported: true,
	},
	TEZOS: {
		ID:               1729,
		Handle:           "tezos",
		Symbol:           "XTZ",
		Name:             "Tezos",
		Decimals:         6,
		BlockTime:        20000,
		MinConfirmations: 0,
		Blockchain:       "Tezos",
		IsTokenSupported: false,
	},
	KIN: {
		ID:               2017,
		Handle:           "kin",
		Symbol:           "KIN",
		Name:             "Kin",
		Decimals:         5,
		BlockTime:        5000,
		MinConfirmations: 0,
		Blockchain:       "Stellar",
		IsTokenSupported: false,
	},
	NEBULAS: {
		ID:               2718,
		Handle:           "nebulas",
		Symbol:           "NAS",
		Name:             "Nebulas",
		Decimals:         18,
		BlockTime:        30000,
		MinConfirmations: 0,
		Blockchain:       "Nebulas",
		IsTokenSupported: false,
	},
	GOCHAIN: {
		ID:               6060,
		Handle:           "gochain",
		Symbol:           "GO",
		Name:             "GoChain GO",
		Decimals:         18,
		BlockTime:        20000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	WANCHAIN: {
		ID:               5718350,
		Handle:           "wanchain",
		Symbol:           "WAN",
		Name:             "Wanchain",
		Decimals:         18,
		BlockTime:        30000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	WAVES: {
		ID:               5741564,
		Handle:           "waves",
		Symbol:           "WAVES",
		Name:             "WAVES",
		Decimals:         8,
		BlockTime:        30000,
		MinConfirmations: 1,
		Blockchain:       "Waves",
		IsTokenSupported: false,
	},
	BITCOIN: {
		ID:               0,
		Handle:           "bitcoin",
		Symbol:           "BTC",
		Name:             "Bitcoin",
		Decimals:         8,
		BlockTime:        600000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: true,
	},
	LITECOIN: {
		ID:               2,
		Handle:           "litecoin",
		Symbol:           "LTC",
		Name:             "Litecoin",
		Decimals:         8,
		BlockTime:        150000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	DOGE: {
		ID:               3,
		Handle:           "doge",
		Symbol:           "DOGE",
		Name:             "Dogecoin",
		Decimals:         8,
		BlockTime:        60000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	DASH: {
		ID:               5,
		Handle:           "dash",
		Symbol:           "DASH",
		Name:             "Dash",
		Decimals:         8,
		BlockTime:        180000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	VIACOIN: {
		ID:               14,
		Handle:           "viacoin",
		Symbol:           "VIA",
		Name:             "Viacoin",
		Decimals:         8,
		BlockTime:        15000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	GROESTLCOIN: {
		ID:               17,
		Handle:           "groestlcoin",
		Symbol:           "GRS",
		Name:             "Groestlcoin",
		Decimals:         8,
		BlockTime:        60000,
		MinConfirmations: 0,
		Blockchain:       "Groestlcoin",
		IsTokenSupported: false,
	},
	ZCASH: {
		ID:               133,
		Handle:           "zcash",
		Symbol:           "ZEC",
		Name:             "Zcash",
		Decimals:         8,
		BlockTime:        150000,
		MinConfirmations: 0,
		Blockchain:       "Zcash",
		IsTokenSupported: false,
	},
	FIRO: {
		ID:               136,
		Handle:           "firo",
		Symbol:           "FIRO",
		Name:             "Firo",
		Decimals:         8,
		BlockTime:        300000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	BITCOINCASH: {
		ID:               145,
		Handle:           "bitcoincash",
		Symbol:           "BCH",
		Name:             "Bitcoin Cash",
		Decimals:         8,
		BlockTime:        600000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	RAVENCOIN: {
		ID:               175,
		Handle:           "ravencoin",
		Symbol:           "RVN",
		Name:             "Raven",
		Decimals:         8,
		BlockTime:        60000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	QTUM: {
		ID:               2301,
		Handle:           "qtum",
		Symbol:           "QTUM",
		Name:             "Qtum",
		Decimals:         8,
		BlockTime:        60000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	ZELCASH: {
		ID:               19167,
		Handle:           "zelcash",
		Symbol:           "ZEL",
		Name:             "Zelcash",
		Decimals:         8,
		BlockTime:        120000,
		MinConfirmations: 0,
		Blockchain:       "Zcash",
		IsTokenSupported: false,
	},
	DECRED: {
		ID:               42,
		Handle:           "decred",
		Symbol:           "DCR",
		Name:             "Decred",
		Decimals:         8,
		BlockTime:        300000,
		MinConfirmations: 0,
		Blockchain:       "Decred",
		IsTokenSupported: false,
	},
	ALGORAND: {
		ID:               283,
		Handle:           "algorand",
		Symbol:           "ALGO",
		Name:             "Algorand",
		Decimals:         6,
		BlockTime:        20000,
		MinConfirmations: 0,
		Blockchain:       "Algorand",
		IsTokenSupported: false,
	},
	NANO: {
		ID:               165,
		Handle:           "nano",
		Symbol:           "XNO",
		Name:             "Nano",
		Decimals:         30,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Nano",
		IsTokenSupported: false,
	},
	DIGIBYTE: {
		ID:               20,
		Handle:           "digibyte",
		Symbol:           "DGB",
		Name:             "DigiByte",
		Decimals:         8,
		BlockTime:        15000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	HARMONY: {
		ID:               1023,
		Handle:           "harmony",
		Symbol:           "ONE",
		Name:             "Harmony",
		Decimals:         18,
		BlockTime:        5000,
		MinConfirmations: 0,
		Blockchain:       "Harmony",
		IsTokenSupported: false,
	},
	KUSAMA: {
		ID:               434,
		Handle:           "kusama",
		Symbol:           "KSM",
		Name:             "Kusama",
		Decimals:         12,
		BlockTime:        6000,
		MinConfirmations: 0,
		Blockchain:       "Kusama",
		IsTokenSupported: false,
	},
	POLKADOT: {
		ID:               354,
		Handle:           "polkadot",
		Symbol:           "DOT",
		Name:             "Polkadot",
		Decimals:         10,
		BlockTime:        6000,
		MinConfirmations: 0,
		Blockchain:       "Polkadot",
		IsTokenSupported: false,
	},
	SOLANA: {
		ID:               501,
		Handle:           "solana",
		Symbol:           "SOL",
		Name:             "Solana",
		Decimals:         9,
		BlockTime:        500,
		MinConfirmations: 0,
		Blockchain:       "Solana",
		IsTokenSupported: true,
	},
	NEAR: {
		ID:               397,
		Handle:           "near",
		Symbol:           "NEAR",
		Name:             "NEAR",
		Decimals:         24,
		BlockTime:        2000,
		MinConfirmations: 0,
		Blockchain:       "NEAR",
		IsTokenSupported: false,
	},
	ELROND: {
		ID:               508,
		Handle:           "elrond",
		Symbol:           "eGLD",
		Name:             "Elrond",
		Decimals:         18,
		BlockTime:        6000,
		MinConfirmations: 0,
		Blockchain:       "ElrondNetwork",
		IsTokenSupported: false,
	},
	SMARTCHAIN: {
		ID:               20000714,
		Handle:           "smartchain",
		Symbol:           "BNB",
		Name:             "Smart Chain",
		Decimals:         18,
		BlockTime:        3000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	FILECOIN: {
		ID:               461,
		Handle:           "filecoin",
		Symbol:           "FIL",
		Name:             "Filecoin",
		Decimals:         18,
		BlockTime:        3000,
		MinConfirmations: 0,
		Blockchain:       "Filecoin",
		IsTokenSupported: false,
	},
	OASIS: {
		ID:               474,
		Handle:           "oasis",
		Symbol:           "ROSE",
		Name:             "Oasis",
		Decimals:         9,
		BlockTime:        6000,
		MinConfirmations: 0,
		Blockchain:       "OasisNetwork",
		IsTokenSupported: false,
	},
	MONACOIN: {
		ID:               22,
		Handle:           "monacoin",
		Symbol:           "MONA",
		Name:             "Monacoin",
		Decimals:         8,
		BlockTime:        90000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	BITCOINGOLD: {
		ID:               156,
		Handle:           "bitcoingold",
		Symbol:           "BTG",
		Name:             "Bitcoin Gold",
		Decimals:         8,
		BlockTime:        600000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	EOS: {
		ID:               194,
		Handle:           "eos",
		Symbol:           "EOS",
		Name:             "EOS",
		Decimals:         4,
		BlockTime:        500,
		MinConfirmations: 0,
		Blockchain:       "EOS",
		IsTokenSupported: false,
	},
	TERRA: {
		ID:               330,
		Handle:           "terra",
		Symbol:           "LUNC",
		Name:             "Terra Classic",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	BAND: {
		ID:               494,
		Handle:           "band",
		Symbol:           "BAND",
		Name:             "BandChain",
		Decimals:         6,
		BlockTime:        2000,
		MinConfirmations: 0,
		Blockchain:       "Cosmos",
		IsTokenSupported: false,
	},
	NEO: {
		ID:               888,
		Handle:           "neo",
		Symbol:           "NEO",
		Name:             "NEO",
		Decimals:         8,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "NEO",
		IsTokenSupported: false,
	},
	CARDANO: {
		ID:               1815,
		Handle:           "cardano",
		Symbol:           "ADA",
		Name:             "Cardano",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Cardano",
		IsTokenSupported: false,
	},
	NULS: {
		ID:               8964,
		Handle:           "nuls",
		Symbol:           "NULS",
		Name:             "NULS",
		Decimals:         8,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "NULS",
		IsTokenSupported: false,
	},
	POLYGON: {
		ID:               966,
		Handle:           "polygon",
		Symbol:           "MATIC",
		Name:             "Polygon",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	THORCHAIN: {
		ID:               931,
		Handle:           "thorchain",
		Symbol:           "RUNE",
		Name:             "THORChain",
		Decimals:         8,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Thorchain",
		IsTokenSupported: false,
	},
	OPTIMISM: {
		ID:               10000070,
		Handle:           "optimism",
		Symbol:           "OETH",
		Name:             "Optimism Ethereum",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	XDAI: {
		ID:               10000100,
		Handle:           "xdai",
		Symbol:           "xDAI",
		Name:             "xDai",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	AVALANCHEC: {
		ID:               10009000,
		Handle:           "avalanchec",
		Symbol:           "AVAX",
		Name:             "Avalanche C-Chain",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	HECO: {
		ID:               10000553,
		Handle:           "heco",
		Symbol:           "HT",
		Name:             "Huobi ECO Chain",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	FANTOM: {
		ID:               10000250,
		Handle:           "fantom",
		Symbol:           "FTM",
		Name:             "Fantom",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	ARBITRUM: {
		ID:               10042221,
		Handle:           "arbitrum",
		Symbol:           "ARETH",
		Name:             "Arbitrum",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	CELO: {
		ID:               52752,
		Handle:           "celo",
		Symbol:           "CELO",
		Name:             "Celo",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	RONIN: {
		ID:               10002020,
		Handle:           "ronin",
		Symbol:           "RON",
		Name:             "Ronin",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	OSMOSIS: {
		ID:               10000118,
		Handle:           "osmosis",
		Symbol:           "OSMO",
		Name:             "Osmosis",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	CRONOS: {
		ID:               10000025,
		Handle:           "cronos",
		Symbol:           "CRO",
		Name:             "Cronos",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	KCC: {
		ID:               10000321,
		Handle:           "kcc",
		Symbol:           "KCS",
		Name:             "KuCoin Community Chain",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	AURORA: {
		ID:               1323161554,
		Handle:           "aurora",
		Symbol:           "AURORAETH",
		Name:             "Aurora",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	KAVAEVM: {
		ID:               10002222,
		Handle:           "kavaevm",
		Symbol:           "KAVA",
		Name:             "KavaEvm",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	METER: {
		ID:               18000,
		Handle:           "meter",
		Symbol:           "MTR",
		Name:             "Meter",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: false,
	},
	EVMOS: {
		ID:               10009001,
		Handle:           "evmos",
		Symbol:           "EVMOS",
		Name:             "Evmos",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	NATIVEEVMOS: {
		ID:               20009001,
		Handle:           "nativeevmos",
		Symbol:           "EVMOS",
		Name:             "NativeEvmos",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	OKC: {
		ID:               996,
		Handle:           "okc",
		Symbol:           "OKT",
		Name:             "OKX Chain",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Ethereum",
		IsTokenSupported: false,
	},
	CRYPTOORG: {
		ID:               394,
		Handle:           "cryptoorg",
		Symbol:           "CRO",
		Name:             "CryptoOrg",
		Decimals:         8,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	APTOS: {
		ID:               637,
		Handle:           "aptos",
		Symbol:           "APTOS",
		Name:             "Aptos",
		Decimals:         8,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Aptos",
		IsTokenSupported: false,
	},
	MOONBEAM: {
		ID:               10001284,
		Handle:           "moonbeam",
		Symbol:           "GLMR",
		Name:             "Moonbeam",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	KLAYTN: {
		ID:               10008217,
		Handle:           "klaytn",
		Symbol:           "KLAY",
		Name:             "Klaytn",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	METIS: {
		ID:               10001088,
		Handle:           "metis",
		Symbol:           "METIS",
		Name:             "Metis",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	MOONRIVER: {
		ID:               10001285,
		Handle:           "moonriver",
		Symbol:           "MOVR",
		Name:             "Moonriver",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 2,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	BOBA: {
		ID:               10000288,
		Handle:           "boba",
		Symbol:           "BOBAETH",
		Name:             "Boba",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 1,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	TON: {
		ID:               607,
		Handle:           "ton",
		Symbol:           "TON",
		Name:             "TON",
		Decimals:         9,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "The Open Network",
		IsTokenSupported: true,
	},
	POLYGONZKEVM: {
		ID:               10001101,
		Handle:           "polygonzkevm",
		Symbol:           "ZKEVM",
		Name:             "Polygon zkEVM",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	ZKSYNC: {
		ID:               10000324,
		Handle:           "zksync",
		Symbol:           "ZKSYNC",
		Name:             "Zksync",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	SUI: {
		ID:               784,
		Handle:           "sui",
		Symbol:           "SUI",
		Name:             "Sui",
		Decimals:         9,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Sui",
		IsTokenSupported: false,
	},
	STRIDE: {
		ID:               40000118,
		Handle:           "stride",
		Symbol:           "STRD",
		Name:             "Stride",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	NEUTRON: {
		ID:               90000118,
		Handle:           "neutron",
		Symbol:           "NTRN",
		Name:             "Neutron",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 10,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	STARGAZE: {
		ID:               20000118,
		Handle:           "stargaze",
		Symbol:           "STARS",
		Name:             "Stargaze",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	NATIVEINJECTIVE: {
		ID:               10000060,
		Handle:           "nativeinjective",
		Symbol:           "INJ",
		Name:             "NativeInjective",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 30,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	CFXEVM: {
		ID:               1030,
		Handle:           "cfxevm",
		Symbol:           "CFX",
		Name:             "Conflux eSpace",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	ACALA: {
		ID:               787,
		Handle:           "acala",
		Symbol:           "ACA",
		Name:             "Acala",
		Decimals:         12,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Polkadot",
		IsTokenSupported: false,
	},
	ACALAEVM: {
		ID:               10000787,
		Handle:           "acalaevm",
		Symbol:           "ACA",
		Name:             "Acala EVM",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 2,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	BASE: {
		ID:               8453,
		Handle:           "base",
		Symbol:           "ETH",
		Name:             "Base",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	AKASH: {
		ID:               17000118,
		Handle:           "akash",
		Symbol:           "AKT",
		Name:             "Akash",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	AGORIC: {
		ID:               564,
		Handle:           "agoric",
		Symbol:           "BLD",
		Name:             "Agoric",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	AXELAR: {
		ID:               50000118,
		Handle:           "axelar",
		Symbol:           "AXL",
		Name:             "Axelar",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	JUNO: {
		ID:               30000118,
		Handle:           "juno",
		Symbol:           "JUNO",
		Name:             "Juno",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	SEI: {
		ID:               19000118,
		Handle:           "sei",
		Symbol:           "SEI",
		Name:             "Sei",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Cosmos",
		IsTokenSupported: false,
	},
	NEON: {
		ID:               245022934,
		Handle:           "neon",
		Symbol:           "NEON",
		Name:             "Neon",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 1,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	OPBNB: {
		ID:               204,
		Handle:           "opbnb",
		Symbol:           "BNB",
		Name:             "OpBNB",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 24,
		Blockchain:       "Ethereum",
		IsTokenSupported: false,
	},
	LINEA: {
		ID:               59144,
		Handle:           "linea",
		Symbol:           "ETH",
		Name:             "Linea",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	GBNB: {
		ID:               5600,
		Handle:           "gbnb",
		Symbol:           "gBNB",
		Name:             "BNB Greenfield",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Greenfield",
		IsTokenSupported: false,
	},
	MANTLE: {
		ID:               5000,
		Handle:           "mantle",
		Symbol:           "MNT",
		Name:             "Mantle",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Ethereum",
		IsTokenSupported: false,
	},
	MANTA: {
		ID:               169,
		Handle:           "manta",
		Symbol:           "ETH",
		Name:             "Manta Pacific",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	ZETACHAIN: {
		ID:               10007000,
		Handle:           "zetachain",
		Symbol:           "ZETA",
		Name:             "NativeZetaChain",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Cosmos",
		IsTokenSupported: false,
	},
	ZETAEVM: {
		ID:               20007000,
		Handle:           "zetaevm",
		Symbol:           "ZETA",
		Name:             "Zeta EVM",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Ethereum",
		IsTokenSupported: false,
	},
	MERLIN: {
		ID:               4200,
		Handle:           "merlin",
		Symbol:           "BTC",
		Name:             "Merlin",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	BLAST: {
		ID:               81457,
		Handle:           "blast",
		Symbol:           "ETH",
		Name:             "Blast",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	SCROLL: {
		ID:               534352,
		Handle:           "scroll",
		Symbol:           "ETH",
		Name:             "Scroll",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	INTERNET_COMPUTER: {
		ID:               223,
		Handle:           "internet_computer",
		Symbol:           "ICP",
		Name:             "Internet Computer",
		Decimals:         8,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Internet Computer",
		IsTokenSupported: false,
	},
	BOUNCEBIT: {
		ID:               6001,
		Handle:           "bouncebit",
		Symbol:           "BB",
		Name:             "BounceBit",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Ethereum",
		IsTokenSupported: false,
	},
	ZKLINKNOVA: {
		ID:               810180,
		Handle:           "zklinknova",
		Symbol:           "ETH",
		Name:             "zkLink Nova",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
}

var Chains = map[string]Coin{
	Ethereum().Handle: {
		ID:               60,
		Handle:           "ethereum",
		Symbol:           "ETH",
		Name:             "Ethereum",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Classic().Handle: {
		ID:               61,
		Handle:           "classic",
		Symbol:           "ETC",
		Name:             "Ethereum Classic",
		Decimals:         18,
		BlockTime:        30000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Icon().Handle: {
		ID:               74,
		Handle:           "icon",
		Symbol:           "ICX",
		Name:             "ICON",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 0,
		Blockchain:       "Icon",
		IsTokenSupported: false,
	},
	Cosmos().Handle: {
		ID:               118,
		Handle:           "cosmos",
		Symbol:           "ATOM",
		Name:             "Cosmos",
		Decimals:         6,
		BlockTime:        5000,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	Ripple().Handle: {
		ID:               144,
		Handle:           "ripple",
		Symbol:           "XRP",
		Name:             "Ripple",
		Decimals:         6,
		BlockTime:        5000,
		MinConfirmations: 0,
		Blockchain:       "Ripple",
		IsTokenSupported: false,
	},
	Stellar().Handle: {
		ID:               148,
		Handle:           "stellar",
		Symbol:           "XLM",
		Name:             "Stellar",
		Decimals:         7,
		BlockTime:        5000,
		MinConfirmations: 0,
		Blockchain:       "Stellar",
		IsTokenSupported: false,
	},
	Poa().Handle: {
		ID:               178,
		Handle:           "poa",
		Symbol:           "POA",
		Name:             "Poa",
		Decimals:         18,
		BlockTime:        5000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Tron().Handle: {
		ID:               195,
		Handle:           "tron",
		Symbol:           "TRX",
		Name:             "Tron",
		Decimals:         6,
		BlockTime:        10000,
		MinConfirmations: 0,
		Blockchain:       "Tron",
		IsTokenSupported: true,
	},
	Fio().Handle: {
		ID:               235,
		Handle:           "fio",
		Symbol:           "FIO",
		Name:             "FIO",
		Decimals:         9,
		BlockTime:        5000,
		MinConfirmations: 0,
		Blockchain:       "FIO",
		IsTokenSupported: false,
	},
	Nimiq().Handle: {
		ID:               242,
		Handle:           "nimiq",
		Symbol:           "NIM",
		Name:             "Nimiq",
		Decimals:         5,
		BlockTime:        60000,
		MinConfirmations: 0,
		Blockchain:       "Nimiq",
		IsTokenSupported: false,
	},
	Iotex().Handle: {
		ID:               304,
		Handle:           "iotex",
		Symbol:           "IOTX",
		Name:             "IoTeX",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 0,
		Blockchain:       "IoTeX",
		IsTokenSupported: false,
	},
	Iotexevm().Handle: {
		ID:               10004689,
		Handle:           "iotexevm",
		Symbol:           "IOTX",
		Name:             "IoTeX Network Mainnet",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Zilliqa().Handle: {
		ID:               313,
		Handle:           "zilliqa",
		Symbol:           "ZIL",
		Name:             "Zilliqa",
		Decimals:         12,
		BlockTime:        30000,
		MinConfirmations: 1,
		Blockchain:       "Zilliqa",
		IsTokenSupported: false,
	},
	Aion().Handle: {
		ID:               425,
		Handle:           "aion",
		Symbol:           "AION",
		Name:             "Aion",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 0,
		Blockchain:       "Aion",
		IsTokenSupported: false,
	},
	Aeternity().Handle: {
		ID:               457,
		Handle:           "aeternity",
		Symbol:           "AE",
		Name:             "Aeternity",
		Decimals:         18,
		BlockTime:        6000,
		MinConfirmations: 0,
		Blockchain:       "Aeternity",
		IsTokenSupported: false,
	},
	Kava().Handle: {
		ID:               459,
		Handle:           "kava",
		Symbol:           "KAVA",
		Name:             "Kava",
		Decimals:         6,
		BlockTime:        5000,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	Theta().Handle: {
		ID:               500,
		Handle:           "theta",
		Symbol:           "THETA",
		Name:             "Theta",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Theta",
		IsTokenSupported: true,
	},
	Binance().Handle: {
		ID:               714,
		Handle:           "binance",
		Symbol:           "BNB",
		Name:             "BNB",
		Decimals:         8,
		BlockTime:        1000,
		MinConfirmations: 2,
		Blockchain:       "Binance",
		IsTokenSupported: true,
	},
	Vechain().Handle: {
		ID:               818,
		Handle:           "vechain",
		Symbol:           "VET",
		Name:             "VeChain Token",
		Decimals:         18,
		BlockTime:        20000,
		MinConfirmations: 0,
		Blockchain:       "Vechain",
		IsTokenSupported: true,
	},
	Callisto().Handle: {
		ID:               820,
		Handle:           "callisto",
		Symbol:           "CLO",
		Name:             "Callisto",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Tomochain().Handle: {
		ID:               889,
		Handle:           "tomochain",
		Symbol:           "TOMO",
		Name:             "TOMO",
		Decimals:         18,
		BlockTime:        4000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Thundertoken().Handle: {
		ID:               1001,
		Handle:           "thundertoken",
		Symbol:           "TT",
		Name:             "ThunderCore",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Ontology().Handle: {
		ID:               1024,
		Handle:           "ontology",
		Symbol:           "ONT",
		Name:             "Ontology",
		Decimals:         0,
		BlockTime:        10000,
		MinConfirmations: 0,
		Blockchain:       "Ontology",
		IsTokenSupported: true,
	},
	Tezos().Handle: {
		ID:               1729,
		Handle:           "tezos",
		Symbol:           "XTZ",
		Name:             "Tezos",
		Decimals:         6,
		BlockTime:        20000,
		MinConfirmations: 0,
		Blockchain:       "Tezos",
		IsTokenSupported: false,
	},
	Kin().Handle: {
		ID:               2017,
		Handle:           "kin",
		Symbol:           "KIN",
		Name:             "Kin",
		Decimals:         5,
		BlockTime:        5000,
		MinConfirmations: 0,
		Blockchain:       "Stellar",
		IsTokenSupported: false,
	},
	Nebulas().Handle: {
		ID:               2718,
		Handle:           "nebulas",
		Symbol:           "NAS",
		Name:             "Nebulas",
		Decimals:         18,
		BlockTime:        30000,
		MinConfirmations: 0,
		Blockchain:       "Nebulas",
		IsTokenSupported: false,
	},
	Gochain().Handle: {
		ID:               6060,
		Handle:           "gochain",
		Symbol:           "GO",
		Name:             "GoChain GO",
		Decimals:         18,
		BlockTime:        20000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Wanchain().Handle: {
		ID:               5718350,
		Handle:           "wanchain",
		Symbol:           "WAN",
		Name:             "Wanchain",
		Decimals:         18,
		BlockTime:        30000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Waves().Handle: {
		ID:               5741564,
		Handle:           "waves",
		Symbol:           "WAVES",
		Name:             "WAVES",
		Decimals:         8,
		BlockTime:        30000,
		MinConfirmations: 1,
		Blockchain:       "Waves",
		IsTokenSupported: false,
	},
	Bitcoin().Handle: {
		ID:               0,
		Handle:           "bitcoin",
		Symbol:           "BTC",
		Name:             "Bitcoin",
		Decimals:         8,
		BlockTime:        600000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: true,
	},
	Litecoin().Handle: {
		ID:               2,
		Handle:           "litecoin",
		Symbol:           "LTC",
		Name:             "Litecoin",
		Decimals:         8,
		BlockTime:        150000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	Doge().Handle: {
		ID:               3,
		Handle:           "doge",
		Symbol:           "DOGE",
		Name:             "Dogecoin",
		Decimals:         8,
		BlockTime:        60000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	Dash().Handle: {
		ID:               5,
		Handle:           "dash",
		Symbol:           "DASH",
		Name:             "Dash",
		Decimals:         8,
		BlockTime:        180000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	Viacoin().Handle: {
		ID:               14,
		Handle:           "viacoin",
		Symbol:           "VIA",
		Name:             "Viacoin",
		Decimals:         8,
		BlockTime:        15000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	Groestlcoin().Handle: {
		ID:               17,
		Handle:           "groestlcoin",
		Symbol:           "GRS",
		Name:             "Groestlcoin",
		Decimals:         8,
		BlockTime:        60000,
		MinConfirmations: 0,
		Blockchain:       "Groestlcoin",
		IsTokenSupported: false,
	},
	Zcash().Handle: {
		ID:               133,
		Handle:           "zcash",
		Symbol:           "ZEC",
		Name:             "Zcash",
		Decimals:         8,
		BlockTime:        150000,
		MinConfirmations: 0,
		Blockchain:       "Zcash",
		IsTokenSupported: false,
	},
	Firo().Handle: {
		ID:               136,
		Handle:           "firo",
		Symbol:           "FIRO",
		Name:             "Firo",
		Decimals:         8,
		BlockTime:        300000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	Bitcoincash().Handle: {
		ID:               145,
		Handle:           "bitcoincash",
		Symbol:           "BCH",
		Name:             "Bitcoin Cash",
		Decimals:         8,
		BlockTime:        600000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	Ravencoin().Handle: {
		ID:               175,
		Handle:           "ravencoin",
		Symbol:           "RVN",
		Name:             "Raven",
		Decimals:         8,
		BlockTime:        60000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	Qtum().Handle: {
		ID:               2301,
		Handle:           "qtum",
		Symbol:           "QTUM",
		Name:             "Qtum",
		Decimals:         8,
		BlockTime:        60000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	Zelcash().Handle: {
		ID:               19167,
		Handle:           "zelcash",
		Symbol:           "ZEL",
		Name:             "Zelcash",
		Decimals:         8,
		BlockTime:        120000,
		MinConfirmations: 0,
		Blockchain:       "Zcash",
		IsTokenSupported: false,
	},
	Decred().Handle: {
		ID:               42,
		Handle:           "decred",
		Symbol:           "DCR",
		Name:             "Decred",
		Decimals:         8,
		BlockTime:        300000,
		MinConfirmations: 0,
		Blockchain:       "Decred",
		IsTokenSupported: false,
	},
	Algorand().Handle: {
		ID:               283,
		Handle:           "algorand",
		Symbol:           "ALGO",
		Name:             "Algorand",
		Decimals:         6,
		BlockTime:        20000,
		MinConfirmations: 0,
		Blockchain:       "Algorand",
		IsTokenSupported: false,
	},
	Nano().Handle: {
		ID:               165,
		Handle:           "nano",
		Symbol:           "XNO",
		Name:             "Nano",
		Decimals:         30,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Nano",
		IsTokenSupported: false,
	},
	Digibyte().Handle: {
		ID:               20,
		Handle:           "digibyte",
		Symbol:           "DGB",
		Name:             "DigiByte",
		Decimals:         8,
		BlockTime:        15000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	Harmony().Handle: {
		ID:               1023,
		Handle:           "harmony",
		Symbol:           "ONE",
		Name:             "Harmony",
		Decimals:         18,
		BlockTime:        5000,
		MinConfirmations: 0,
		Blockchain:       "Harmony",
		IsTokenSupported: false,
	},
	Kusama().Handle: {
		ID:               434,
		Handle:           "kusama",
		Symbol:           "KSM",
		Name:             "Kusama",
		Decimals:         12,
		BlockTime:        6000,
		MinConfirmations: 0,
		Blockchain:       "Kusama",
		IsTokenSupported: false,
	},
	Polkadot().Handle: {
		ID:               354,
		Handle:           "polkadot",
		Symbol:           "DOT",
		Name:             "Polkadot",
		Decimals:         10,
		BlockTime:        6000,
		MinConfirmations: 0,
		Blockchain:       "Polkadot",
		IsTokenSupported: false,
	},
	Solana().Handle: {
		ID:               501,
		Handle:           "solana",
		Symbol:           "SOL",
		Name:             "Solana",
		Decimals:         9,
		BlockTime:        500,
		MinConfirmations: 0,
		Blockchain:       "Solana",
		IsTokenSupported: true,
	},
	Near().Handle: {
		ID:               397,
		Handle:           "near",
		Symbol:           "NEAR",
		Name:             "NEAR",
		Decimals:         24,
		BlockTime:        2000,
		MinConfirmations: 0,
		Blockchain:       "NEAR",
		IsTokenSupported: false,
	},
	Elrond().Handle: {
		ID:               508,
		Handle:           "elrond",
		Symbol:           "eGLD",
		Name:             "Elrond",
		Decimals:         18,
		BlockTime:        6000,
		MinConfirmations: 0,
		Blockchain:       "ElrondNetwork",
		IsTokenSupported: false,
	},
	Smartchain().Handle: {
		ID:               20000714,
		Handle:           "smartchain",
		Symbol:           "BNB",
		Name:             "Smart Chain",
		Decimals:         18,
		BlockTime:        3000,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Filecoin().Handle: {
		ID:               461,
		Handle:           "filecoin",
		Symbol:           "FIL",
		Name:             "Filecoin",
		Decimals:         18,
		BlockTime:        3000,
		MinConfirmations: 0,
		Blockchain:       "Filecoin",
		IsTokenSupported: false,
	},
	Oasis().Handle: {
		ID:               474,
		Handle:           "oasis",
		Symbol:           "ROSE",
		Name:             "Oasis",
		Decimals:         9,
		BlockTime:        6000,
		MinConfirmations: 0,
		Blockchain:       "OasisNetwork",
		IsTokenSupported: false,
	},
	Monacoin().Handle: {
		ID:               22,
		Handle:           "monacoin",
		Symbol:           "MONA",
		Name:             "Monacoin",
		Decimals:         8,
		BlockTime:        90000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	Bitcoingold().Handle: {
		ID:               156,
		Handle:           "bitcoingold",
		Symbol:           "BTG",
		Name:             "Bitcoin Gold",
		Decimals:         8,
		BlockTime:        600000,
		MinConfirmations: 0,
		Blockchain:       "Bitcoin",
		IsTokenSupported: false,
	},
	Eos().Handle: {
		ID:               194,
		Handle:           "eos",
		Symbol:           "EOS",
		Name:             "EOS",
		Decimals:         4,
		BlockTime:        500,
		MinConfirmations: 0,
		Blockchain:       "EOS",
		IsTokenSupported: false,
	},
	Terra().Handle: {
		ID:               330,
		Handle:           "terra",
		Symbol:           "LUNC",
		Name:             "Terra Classic",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	Band().Handle: {
		ID:               494,
		Handle:           "band",
		Symbol:           "BAND",
		Name:             "BandChain",
		Decimals:         6,
		BlockTime:        2000,
		MinConfirmations: 0,
		Blockchain:       "Cosmos",
		IsTokenSupported: false,
	},
	Neo().Handle: {
		ID:               888,
		Handle:           "neo",
		Symbol:           "NEO",
		Name:             "NEO",
		Decimals:         8,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "NEO",
		IsTokenSupported: false,
	},
	Cardano().Handle: {
		ID:               1815,
		Handle:           "cardano",
		Symbol:           "ADA",
		Name:             "Cardano",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Cardano",
		IsTokenSupported: false,
	},
	Nuls().Handle: {
		ID:               8964,
		Handle:           "nuls",
		Symbol:           "NULS",
		Name:             "NULS",
		Decimals:         8,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "NULS",
		IsTokenSupported: false,
	},
	Polygon().Handle: {
		ID:               966,
		Handle:           "polygon",
		Symbol:           "MATIC",
		Name:             "Polygon",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Thorchain().Handle: {
		ID:               931,
		Handle:           "thorchain",
		Symbol:           "RUNE",
		Name:             "THORChain",
		Decimals:         8,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Thorchain",
		IsTokenSupported: false,
	},
	Optimism().Handle: {
		ID:               10000070,
		Handle:           "optimism",
		Symbol:           "OETH",
		Name:             "Optimism Ethereum",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Xdai().Handle: {
		ID:               10000100,
		Handle:           "xdai",
		Symbol:           "xDAI",
		Name:             "xDai",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Avalanchec().Handle: {
		ID:               10009000,
		Handle:           "avalanchec",
		Symbol:           "AVAX",
		Name:             "Avalanche C-Chain",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Heco().Handle: {
		ID:               10000553,
		Handle:           "heco",
		Symbol:           "HT",
		Name:             "Huobi ECO Chain",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Fantom().Handle: {
		ID:               10000250,
		Handle:           "fantom",
		Symbol:           "FTM",
		Name:             "Fantom",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Arbitrum().Handle: {
		ID:               10042221,
		Handle:           "arbitrum",
		Symbol:           "ARETH",
		Name:             "Arbitrum",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Celo().Handle: {
		ID:               52752,
		Handle:           "celo",
		Symbol:           "CELO",
		Name:             "Celo",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Ronin().Handle: {
		ID:               10002020,
		Handle:           "ronin",
		Symbol:           "RON",
		Name:             "Ronin",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Osmosis().Handle: {
		ID:               10000118,
		Handle:           "osmosis",
		Symbol:           "OSMO",
		Name:             "Osmosis",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	Cronos().Handle: {
		ID:               10000025,
		Handle:           "cronos",
		Symbol:           "CRO",
		Name:             "Cronos",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Kcc().Handle: {
		ID:               10000321,
		Handle:           "kcc",
		Symbol:           "KCS",
		Name:             "KuCoin Community Chain",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Aurora().Handle: {
		ID:               1323161554,
		Handle:           "aurora",
		Symbol:           "AURORAETH",
		Name:             "Aurora",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Kavaevm().Handle: {
		ID:               10002222,
		Handle:           "kavaevm",
		Symbol:           "KAVA",
		Name:             "KavaEvm",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Meter().Handle: {
		ID:               18000,
		Handle:           "meter",
		Symbol:           "MTR",
		Name:             "Meter",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: false,
	},
	Evmos().Handle: {
		ID:               10009001,
		Handle:           "evmos",
		Symbol:           "EVMOS",
		Name:             "Evmos",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Nativeevmos().Handle: {
		ID:               20009001,
		Handle:           "nativeevmos",
		Symbol:           "EVMOS",
		Name:             "NativeEvmos",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	Okc().Handle: {
		ID:               996,
		Handle:           "okc",
		Symbol:           "OKT",
		Name:             "OKX Chain",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Ethereum",
		IsTokenSupported: false,
	},
	Cryptoorg().Handle: {
		ID:               394,
		Handle:           "cryptoorg",
		Symbol:           "CRO",
		Name:             "CryptoOrg",
		Decimals:         8,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	Aptos().Handle: {
		ID:               637,
		Handle:           "aptos",
		Symbol:           "APTOS",
		Name:             "Aptos",
		Decimals:         8,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Aptos",
		IsTokenSupported: false,
	},
	Moonbeam().Handle: {
		ID:               10001284,
		Handle:           "moonbeam",
		Symbol:           "GLMR",
		Name:             "Moonbeam",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Klaytn().Handle: {
		ID:               10008217,
		Handle:           "klaytn",
		Symbol:           "KLAY",
		Name:             "Klaytn",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Metis().Handle: {
		ID:               10001088,
		Handle:           "metis",
		Symbol:           "METIS",
		Name:             "Metis",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Moonriver().Handle: {
		ID:               10001285,
		Handle:           "moonriver",
		Symbol:           "MOVR",
		Name:             "Moonriver",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 2,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Boba().Handle: {
		ID:               10000288,
		Handle:           "boba",
		Symbol:           "BOBAETH",
		Name:             "Boba",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 1,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Ton().Handle: {
		ID:               607,
		Handle:           "ton",
		Symbol:           "TON",
		Name:             "TON",
		Decimals:         9,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "The Open Network",
		IsTokenSupported: true,
	},
	Polygonzkevm().Handle: {
		ID:               10001101,
		Handle:           "polygonzkevm",
		Symbol:           "ZKEVM",
		Name:             "Polygon zkEVM",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Zksync().Handle: {
		ID:               10000324,
		Handle:           "zksync",
		Symbol:           "ZKSYNC",
		Name:             "Zksync",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Sui().Handle: {
		ID:               784,
		Handle:           "sui",
		Symbol:           "SUI",
		Name:             "Sui",
		Decimals:         9,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Sui",
		IsTokenSupported: false,
	},
	Stride().Handle: {
		ID:               40000118,
		Handle:           "stride",
		Symbol:           "STRD",
		Name:             "Stride",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	Neutron().Handle: {
		ID:               90000118,
		Handle:           "neutron",
		Symbol:           "NTRN",
		Name:             "Neutron",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 10,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	Stargaze().Handle: {
		ID:               20000118,
		Handle:           "stargaze",
		Symbol:           "STARS",
		Name:             "Stargaze",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	Nativeinjective().Handle: {
		ID:               10000060,
		Handle:           "nativeinjective",
		Symbol:           "INJ",
		Name:             "NativeInjective",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 30,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	Cfxevm().Handle: {
		ID:               1030,
		Handle:           "cfxevm",
		Symbol:           "CFX",
		Name:             "Conflux eSpace",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 36,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Acala().Handle: {
		ID:               787,
		Handle:           "acala",
		Symbol:           "ACA",
		Name:             "Acala",
		Decimals:         12,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Polkadot",
		IsTokenSupported: false,
	},
	Acalaevm().Handle: {
		ID:               10000787,
		Handle:           "acalaevm",
		Symbol:           "ACA",
		Name:             "Acala EVM",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 2,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Base().Handle: {
		ID:               8453,
		Handle:           "base",
		Symbol:           "ETH",
		Name:             "Base",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 12,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Akash().Handle: {
		ID:               17000118,
		Handle:           "akash",
		Symbol:           "AKT",
		Name:             "Akash",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	Agoric().Handle: {
		ID:               564,
		Handle:           "agoric",
		Symbol:           "BLD",
		Name:             "Agoric",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	Axelar().Handle: {
		ID:               50000118,
		Handle:           "axelar",
		Symbol:           "AXL",
		Name:             "Axelar",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	Juno().Handle: {
		ID:               30000118,
		Handle:           "juno",
		Symbol:           "JUNO",
		Name:             "Juno",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Cosmos",
		IsTokenSupported: true,
	},
	Sei().Handle: {
		ID:               19000118,
		Handle:           "sei",
		Symbol:           "SEI",
		Name:             "Sei",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Cosmos",
		IsTokenSupported: false,
	},
	Neon().Handle: {
		ID:               245022934,
		Handle:           "neon",
		Symbol:           "NEON",
		Name:             "Neon",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 1,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Opbnb().Handle: {
		ID:               204,
		Handle:           "opbnb",
		Symbol:           "BNB",
		Name:             "OpBNB",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 24,
		Blockchain:       "Ethereum",
		IsTokenSupported: false,
	},
	Linea().Handle: {
		ID:               59144,
		Handle:           "linea",
		Symbol:           "ETH",
		Name:             "Linea",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 7,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Gbnb().Handle: {
		ID:               5600,
		Handle:           "gbnb",
		Symbol:           "gBNB",
		Name:             "BNB Greenfield",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Greenfield",
		IsTokenSupported: false,
	},
	Mantle().Handle: {
		ID:               5000,
		Handle:           "mantle",
		Symbol:           "MNT",
		Name:             "Mantle",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Ethereum",
		IsTokenSupported: false,
	},
	Manta().Handle: {
		ID:               169,
		Handle:           "manta",
		Symbol:           "ETH",
		Name:             "Manta Pacific",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Zetachain().Handle: {
		ID:               10007000,
		Handle:           "zetachain",
		Symbol:           "ZETA",
		Name:             "NativeZetaChain",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Cosmos",
		IsTokenSupported: false,
	},
	Zetaevm().Handle: {
		ID:               20007000,
		Handle:           "zetaevm",
		Symbol:           "ZETA",
		Name:             "Zeta EVM",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Ethereum",
		IsTokenSupported: false,
	},
	Merlin().Handle: {
		ID:               4200,
		Handle:           "merlin",
		Symbol:           "BTC",
		Name:             "Merlin",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Blast().Handle: {
		ID:               81457,
		Handle:           "blast",
		Symbol:           "ETH",
		Name:             "Blast",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Scroll().Handle: {
		ID:               534352,
		Handle:           "scroll",
		Symbol:           "ETH",
		Name:             "Scroll",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
	Internet_computer().Handle: {
		ID:               223,
		Handle:           "internet_computer",
		Symbol:           "ICP",
		Name:             "Internet Computer",
		Decimals:         8,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Internet Computer",
		IsTokenSupported: false,
	},
	Bouncebit().Handle: {
		ID:               6001,
		Handle:           "bouncebit",
		Symbol:           "BB",
		Name:             "BounceBit",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Ethereum",
		IsTokenSupported: false,
	},
	Zklinknova().Handle: {
		ID:               810180,
		Handle:           "zklinknova",
		Symbol:           "ETH",
		Name:             "zkLink Nova",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		Blockchain:       "Ethereum",
		IsTokenSupported: true,
	},
}

func Ethereum() Coin {
	return Coins[ETHEREUM]
}

func Classic() Coin {
	return Coins[CLASSIC]
}

func Icon() Coin {
	return Coins[ICON]
}

func Cosmos() Coin {
	return Coins[COSMOS]
}

func Ripple() Coin {
	return Coins[RIPPLE]
}

func Stellar() Coin {
	return Coins[STELLAR]
}

func Poa() Coin {
	return Coins[POA]
}

func Tron() Coin {
	return Coins[TRON]
}

func Fio() Coin {
	return Coins[FIO]
}

func Nimiq() Coin {
	return Coins[NIMIQ]
}

func Iotex() Coin {
	return Coins[IOTEX]
}

func Iotexevm() Coin {
	return Coins[IOTEXEVM]
}

func Zilliqa() Coin {
	return Coins[ZILLIQA]
}

func Aion() Coin {
	return Coins[AION]
}

func Aeternity() Coin {
	return Coins[AETERNITY]
}

func Kava() Coin {
	return Coins[KAVA]
}

func Theta() Coin {
	return Coins[THETA]
}

func Binance() Coin {
	return Coins[BINANCE]
}

func Vechain() Coin {
	return Coins[VECHAIN]
}

func Callisto() Coin {
	return Coins[CALLISTO]
}

func Tomochain() Coin {
	return Coins[TOMOCHAIN]
}

func Thundertoken() Coin {
	return Coins[THUNDERTOKEN]
}

func Ontology() Coin {
	return Coins[ONTOLOGY]
}

func Tezos() Coin {
	return Coins[TEZOS]
}

func Kin() Coin {
	return Coins[KIN]
}

func Nebulas() Coin {
	return Coins[NEBULAS]
}

func Gochain() Coin {
	return Coins[GOCHAIN]
}

func Wanchain() Coin {
	return Coins[WANCHAIN]
}

func Waves() Coin {
	return Coins[WAVES]
}

func Bitcoin() Coin {
	return Coins[BITCOIN]
}

func Litecoin() Coin {
	return Coins[LITECOIN]
}

func Doge() Coin {
	return Coins[DOGE]
}

func Dash() Coin {
	return Coins[DASH]
}

func Viacoin() Coin {
	return Coins[VIACOIN]
}

func Groestlcoin() Coin {
	return Coins[GROESTLCOIN]
}

func Zcash() Coin {
	return Coins[ZCASH]
}

func Firo() Coin {
	return Coins[FIRO]
}

func Bitcoincash() Coin {
	return Coins[BITCOINCASH]
}

func Ravencoin() Coin {
	return Coins[RAVENCOIN]
}

func Qtum() Coin {
	return Coins[QTUM]
}

func Zelcash() Coin {
	return Coins[ZELCASH]
}

func Decred() Coin {
	return Coins[DECRED]
}

func Algorand() Coin {
	return Coins[ALGORAND]
}

func Nano() Coin {
	return Coins[NANO]
}

func Digibyte() Coin {
	return Coins[DIGIBYTE]
}

func Harmony() Coin {
	return Coins[HARMONY]
}

func Kusama() Coin {
	return Coins[KUSAMA]
}

func Polkadot() Coin {
	return Coins[POLKADOT]
}

func Solana() Coin {
	return Coins[SOLANA]
}

func Near() Coin {
	return Coins[NEAR]
}

func Elrond() Coin {
	return Coins[ELROND]
}

func Smartchain() Coin {
	return Coins[SMARTCHAIN]
}

func Filecoin() Coin {
	return Coins[FILECOIN]
}

func Oasis() Coin {
	return Coins[OASIS]
}

func Monacoin() Coin {
	return Coins[MONACOIN]
}

func Bitcoingold() Coin {
	return Coins[BITCOINGOLD]
}

func Eos() Coin {
	return Coins[EOS]
}

func Terra() Coin {
	return Coins[TERRA]
}

func Band() Coin {
	return Coins[BAND]
}

func Neo() Coin {
	return Coins[NEO]
}

func Cardano() Coin {
	return Coins[CARDANO]
}

func Nuls() Coin {
	return Coins[NULS]
}

func Polygon() Coin {
	return Coins[POLYGON]
}

func Thorchain() Coin {
	return Coins[THORCHAIN]
}

func Optimism() Coin {
	return Coins[OPTIMISM]
}

func Xdai() Coin {
	return Coins[XDAI]
}

func Avalanchec() Coin {
	return Coins[AVALANCHEC]
}

func Heco() Coin {
	return Coins[HECO]
}

func Fantom() Coin {
	return Coins[FANTOM]
}

func Arbitrum() Coin {
	return Coins[ARBITRUM]
}

func Celo() Coin {
	return Coins[CELO]
}

func Ronin() Coin {
	return Coins[RONIN]
}

func Osmosis() Coin {
	return Coins[OSMOSIS]
}

func Cronos() Coin {
	return Coins[CRONOS]
}

func Kcc() Coin {
	return Coins[KCC]
}

func Aurora() Coin {
	return Coins[AURORA]
}

func Kavaevm() Coin {
	return Coins[KAVAEVM]
}

func Meter() Coin {
	return Coins[METER]
}

func Evmos() Coin {
	return Coins[EVMOS]
}

func Nativeevmos() Coin {
	return Coins[NATIVEEVMOS]
}

func Okc() Coin {
	return Coins[OKC]
}

func Cryptoorg() Coin {
	return Coins[CRYPTOORG]
}

func Aptos() Coin {
	return Coins[APTOS]
}

func Moonbeam() Coin {
	return Coins[MOONBEAM]
}

func Klaytn() Coin {
	return Coins[KLAYTN]
}

func Metis() Coin {
	return Coins[METIS]
}

func Moonriver() Coin {
	return Coins[MOONRIVER]
}

func Boba() Coin {
	return Coins[BOBA]
}

func Ton() Coin {
	return Coins[TON]
}

func Polygonzkevm() Coin {
	return Coins[POLYGONZKEVM]
}

func Zksync() Coin {
	return Coins[ZKSYNC]
}

func Sui() Coin {
	return Coins[SUI]
}

func Stride() Coin {
	return Coins[STRIDE]
}

func Neutron() Coin {
	return Coins[NEUTRON]
}

func Stargaze() Coin {
	return Coins[STARGAZE]
}

func Nativeinjective() Coin {
	return Coins[NATIVEINJECTIVE]
}

func Cfxevm() Coin {
	return Coins[CFXEVM]
}

func Acala() Coin {
	return Coins[ACALA]
}

func Acalaevm() Coin {
	return Coins[ACALAEVM]
}

func Base() Coin {
	return Coins[BASE]
}

func Akash() Coin {
	return Coins[AKASH]
}

func Agoric() Coin {
	return Coins[AGORIC]
}

func Axelar() Coin {
	return Coins[AXELAR]
}

func Juno() Coin {
	return Coins[JUNO]
}

func Sei() Coin {
	return Coins[SEI]
}

func Neon() Coin {
	return Coins[NEON]
}

func Opbnb() Coin {
	return Coins[OPBNB]
}

func Linea() Coin {
	return Coins[LINEA]
}

func Gbnb() Coin {
	return Coins[GBNB]
}

func Mantle() Coin {
	return Coins[MANTLE]
}

func Manta() Coin {
	return Coins[MANTA]
}

func Zetachain() Coin {
	return Coins[ZETACHAIN]
}

func Zetaevm() Coin {
	return Coins[ZETAEVM]
}

func Merlin() Coin {
	return Coins[MERLIN]
}

func Blast() Coin {
	return Coins[BLAST]
}

func Scroll() Coin {
	return Coins[SCROLL]
}

func Internet_computer() Coin {
	return Coins[INTERNET_COMPUTER]
}

func Bouncebit() Coin {
	return Coins[BOUNCEBIT]
}

func Zklinknova() Coin {
	return Coins[ZKLINKNOVA]
}

